const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{createRequire}=require('node:module');
const {normalizeCard,buildScience}=require('../native/lib/observation-card');
const old={id:'one',speciesId:'海芋',photoPath:'/original',artPhotoPath:'/art',finishKey:'holo'};
const normalized=normalizeCard(old);
assert.equal(normalized.originalPhotoAsset.localPath,'/original');
assert.equal(normalized.artAsset.localPath,'/art');
assert.equal(normalized.canonicalSpeciesId,'海芋');
assert.equal(normalized.schemaVersion,undefined,'legacy is not falsely promoted');
assert.equal(old.originalPhotoAsset,undefined);
assert.equal(normalizeCard({artPhotoPath:'/art'}).originalPhotoAsset.localPath,'');
const modern={schemaVersion:2,canonicalSpeciesId:'kingfisher',originalPhotoAsset:{localPath:'/v2',fileId:'cloud://original'},artAsset:{localPath:'/painting',fileId:''}};
assert.deepEqual(normalizeCard(modern),{...modern,speciesId:'kingfisher',cardType:'original_observation',artworkState:'legacy_private',countsAsDiscovery:true,discoveryNumber:null});
normalized.originalPhotoAsset.localPath='changed';assert.equal(old.photoPath,'/original');
assert.equal(buildScience({}).status,'missing');
const science=buildScience({know:'可信知识',iucn:'LC',protection:'三有保护',facts:[{title:'一',detail:'二'}],untrusted:'ignore'});
assert.equal(science.fields.knowledge,'可信知识');assert.equal(science.fields.iucn,'LC');assert.equal(science.fields.protection,'三有保护');assert.equal(science.fields.untrusted,undefined);assert.equal(science.status,'available');
assert.equal(buildScience({knowledge:'优先',know:'旧'}).fields.knowledge,'优先');
let app;const appFile=require.resolve('../app.js');vm.runInNewContext(fs.readFileSync(appFile,'utf8'),{App:a=>app=a,require:createRequire(appFile),wx:{getStorageSync:()=>null}});
assert.equal(app.decorate({speciesId:'kingfisher'}).date,'');
assert.equal(app.decorate({speciesId:'kingfisher',createdAt:'bad'}).date,'');
const decorated=app.decorate({...modern,createdAt:1000});assert.equal(decorated.originalPhotoAsset.localPath,'/v2');assert.equal(decorated.schemaVersion,2);
console.log('PASS CardV2 compatibility, trusted science and truthful dates');
