const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..'),storage=new Map();let app;const wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,structuredClone(v)),removeStorageSync:k=>storage.delete(k),showModal:o=>o.success&&o.success({confirm:false}),showToast(){}};
vm.runInNewContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),{App:a=>app=a,wx,Date,Math,Set});
assert.deepEqual(app.finishes.map(f=>f.probability).join(','),'72,20,7,1');
for(const [v,key] of [[0,'standard'],[71.99,'standard'],[72,'holo'],[91.99,'holo'],[92,'alt'],[98.99,'alt'],[99,'numbered']])assert.equal(app.drawFinish(v).key,key);
assert.throws(()=>app.prepareCard('kingfisher'));
app.saveDraft({photoPath:'wxfile://saved.jpg',mode:'unknown'});
const first=app.prepareCard('kingfisher');assert.equal(first.photoPath,'wxfile://saved.jpg');
assert.equal(app.prepareCard('kingfisher').id,first.id);
assert.throws(()=>app.prepareCard('ibis'),/已制卡/);
app.addCard(first);app.addCard(first);assert.equal(app.getCards().length,1);
app.saveDraft({photoPath:'wxfile://second.jpg',mode:'ready'});
const second=app.prepareCard('kingfisher');app.addCard(second);assert.equal(app.getCards().length,2);assert.equal(new Set(app.getCards().map(c=>c.speciesId)).size,1);
const old={id:'legacy',speciesId:'ibis',photoPath:'wxfile://old.jpg'};app.addCard(old);assert.equal(app.decorate(old).finishKey,'numbered');assert.match(app.decorate(old).protection,/一级/);
const retained=app.getDraft();const original=wx.setStorageSync;wx.setStorageSync=()=>{throw new Error('full')};assert.throws(()=>app.saveDraft({photoPath:'wxfile://bad.jpg'}));assert.equal(app.getDraft().photoPath,retained.photoPath);wx.setStorageSync=original;
let page;const timers=[],observeRequire=require('node:module').createRequire(path.join(root,'native/pages/observe/index.js'));vm.runInNewContext(fs.readFileSync(path.join(root,'native/pages/observe/index.js'),'utf8'),{Page:p=>page=p,getApp:()=>app,wx,setTimeout:fn=>(timers.push(fn),timers.length),clearTimeout:()=>{},Date,Object,require:observeRequire});page.data={...page.data,photoPath:'wxfile://second.jpg'};page.setData=function(p){Object.assign(this.data,p)};page.identify();page.onHide();if(timers[0])timers[0]();assert.equal(page.data.mode,'empty');
page.identify();assert.equal(page.data.recognitionStatus,'unavailable');assert.equal(app.getDraft().photoPath,'wxfile://second.jpg');assert.equal(page.data.species,null);
let failed=false;wx.saveFile=({fail})=>fail();wx.showModal=()=>failed=true;page.persist('wxfile://temporary.jpg');assert.equal(failed,false);assert.equal(app.getObservation().photoPath,'wxfile://temporary.jpg');assert.equal(app.getDrafts().some(d=>d.photoPath==='wxfile://temporary.jpg'),false);
console.log('PASS: probability boundaries, legacy data, durable drafts, unknown result, late cancellation, failed persistence, idempotent preparation/filing, species conflicts and duplicate counts');
