const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const lib=require(path.join(__dirname,'../native/lib/card-export.js'));
const card={id:'private-123',speciesId:'ibis',zh:'朱鹮',photoPath:'wxfile://private.jpg',note:'private note',protection:'国家一级保护动物'};
const share=lib.publicShare(card);assert.ok(share.path.includes('sample_ibis'));assert.ok(!JSON.stringify(share).includes('private'));assert.ok(share.imageUrl.endsWith('/assets/images/ibis.jpg'));
assert.deepEqual(lib.PRINT_SPEC,{width:821,height:1121,trimWidth:750,trimHeight:1050,bleedMm:3,dpi:300});
assert.equal(lib.exportPlan(card,'share').backs,true);assert.equal(lib.exportPlan({...card,protection:''},'share').backs,false);
assert.equal(lib.exportPlan(card,'printFront').height,1121);assert.equal(lib.exportPlan(card,'printBack').width,821);
const route=fs.readFileSync(path.join(__dirname,'../native/pages/card/index.js'),'utf8');assert.ok(route.includes('onShareAppMessage'));
assert.ok(route.includes("decodeBack(canvas,card,current)"),'share and print export predecode the same species illustration');
assert.equal((route.match(/exportImage\(mode\)/g)||[]).length,1,'one export handler owns every mode');
assert.ok(route.includes('openPhotoSettings')&&route.includes('重新选择照片'),'export failure offers recovery actions');
console.log('PASS public-only share route, protected front/back composition and print pixel specification');
const draws=[];const ctx={setFillStyle(){},fillRect(...a){draws.push(['rect',...a])},setFontSize(){},measureText:t=>({width:t.length*15}),fillText(...a){draws.push(['text',...a])},save(){},beginPath(){},rect(){},clip(){},drawImage(...a){draws.push(['image',...a])},restore(){},setStrokeStyle(){},moveTo(){},lineTo(){},stroke(){},setLineWidth(){},setTextBaseline(){}};
lib.render(ctx,{...card,finish:'珍藏',finishKey:'numbered',latin:'Nipponia nippon',no:'No.0021'},lib.exportPlan(card,'share'),{path:card.photoPath,width:1000,height:600});
assert.equal(draws.filter(d=>d[0]==='image').length,1,'only front contains image');assert.ok(draws.some(d=>d[0]==='text'&&d[1]===card.protection),'protected share includes full protection');assert.ok(draws.some(d=>d[0]==='rect'&&d[2]===1161&&d[3]===821&&d[4]===1121));
draws.length=0;lib.render(ctx,card,lib.exportPlan(card,'printBack'),{path:card.photoPath,width:600,height:800},{path:'/assets/illustrations/ibis.png'});assert.equal(draws.filter(d=>d[0]==='image').length,1,'printed back includes mapped illustration');
console.log('PASS renderer front/back composition, protection text and picture-free print back');
 assert.equal(lib.printQuality({width:821,height:855},'printFront').effectiveDpi,300);
 assert.equal(lib.printQuality({width:1642,height:855},'printFront').effectiveDpi,300,'cover crop uses limiting source dimension');
 assert.equal(lib.printQuality({width:400,height:800},'printFront').qualified,false);
 assert.ok(lib.printQuality({width:400,height:800},'printFront').message.includes('低于目标'));
 assert.equal(lib.printQuality({},'printBack').effectiveDpi,null);
 draws.length=0;
 lib.render(ctx,{...card,zh:'超长物种名称'.repeat(25),latin:'Long scientific name '.repeat(20),family:'分类'.repeat(60),tagline:'札记'.repeat(100),factTitle:'行为'.repeat(100),habitat:'环境'.repeat(100),season:'全年'.repeat(40),iucn:'濒危'.repeat(30)},lib.exportPlan(card,'printBack'),{});
 const texts=draws.filter(d=>d[0]==='text');assert.ok(texts.every(d=>d[2]>=71));
 assert.ok(texts.filter(d=>d[3]<850).every(d=>d[3]<=800),'science cannot enter fixed protection band');
 assert.ok(texts.some(d=>d[1]===card.protection));
 draws.length=0;lib.render(ctx,{...card,finish:'珍藏'},lib.exportPlan(card,'printFront'),{path:'p',width:821,height:855});
 const pill=draws.findIndex(d=>d[0]==='rect'&&d[1]===540&&d[2]===71);
 const label=draws.findIndex(d=>d[0]==='text'&&d[1]==='珍藏');assert.ok(pill>=0&&pill<label);
 assert.ok(draws.filter(d=>d[0]==='text').every(d=>d[2]>=71));
 console.log('PASS effective DPI, safe-area text, opaque finish pill and longest science reserved protection band');
