const app=getApp(),{buildProfile,checkIn}=require('../../lib/profile-model')
Page({
  badgeError(e){this.setData({['badgeErrors.'+e.currentTarget.dataset.key]:true})},
  data:{profile:null,notes:[],showLocation:false,reduce:false},onShow(){this.refresh()},
  refresh(){const {realCards,locationFreeCard}=require('../../lib/collection-model'),cards=realCards(app.getCards()).map(c=>app.decorate(locationFreeCard(c))).filter(Boolean),state=wx.getStorageSync('nature.profile.v1')||{},profile=buildProfile(cards,state),notes=cards.map(card=>({id:card.id,zh:card.zh,text:wx.getStorageSync('nature.note.'+card.id)||'',image:card.photoPath||card.image})).filter(n=>n.text.trim()).slice().reverse().slice(0,3),savedLocation=wx.getStorageSync('nature.showLocation'),badges=app.getBadges?app.getBadges().badges||[]:[];profile.stats.badges=badges.filter(b=>b.earned).length;profile.stats.notes=cards.filter(c=>String(wx.getStorageSync('nature.note.'+c.id)||'').trim()).length;this.setData({profile,notes,showLocation:savedLocation!==false,reduce:!!wx.getStorageSync('nature.reduceMotion'),badges})},
  chooseNote(){wx.reLaunch({url:'/native/pages/library/index'})},
  checkin(){const state=wx.getStorageSync('nature.profile.v1')||{},result=checkIn(state,new Date().toDateString());wx.setStorageSync('nature.profile.v1',result.state);this.refresh();wx.showToast({title:result.pointsAdded?'打卡 +2':'今天已打卡'})},
  toggleLocation(){const next=!this.data.showLocation;wx.setStorageSync('nature.showLocation',next);this.setData({showLocation:next})},toggleMotion(){const next=!this.data.reduce;wx.setStorageSync('nature.reduceMotion',next);this.setData({reduce:next})},settings(){wx.navigateTo({url:'/native/pages/settings/index'})},openNote(e){const id=e.currentTarget.dataset.id;if(id.indexOf('-note')===-1&&id!=='red-bellied-pheasant')wx.navigateTo({url:'/native/pages/card/index?id='+id})}
})
