const app=getApp()
const {membershipView,socialView}=require('../../lib/availability-model')
const {hasConsent,setConsent}=require('../../lib/recognition-consent')
const recoveryConsent=require('../../lib/recovery-consent')
const {track}=require('../../lib/analytics')
Page({
 ...require('../../lib/settings-services').serviceMethods(wx,app),
 async checkCloudPrivacy(){if(this.data.privacyBusy)return;this.setData({privacyBusy:true});try{const result=await require('../../lib/cloud-privacy').privacyAction('status');this.setData({privacyStatus:result.status,privacyMessage:result.label})}catch(e){this.setData({privacyMessage:'暂时无法连接云端清理服务，请稍后重试。'})}finally{this.setData({privacyBusy:false})}},
 requestCloudErasure(){if(this.data.privacyBusy)return;wx.showModal({title:'申请清除云端个人数据？',content:'将停止该账号的识别、生成和分享，删除私有照片及非财务个人记录。支付对账记录依法保留；公共物种插画不受影响。本机数据可另行清除。',confirmText:'继续',success:r=>{if(!r.confirm)return;wx.showModal({title:'再次确认云端清除',content:'此操作不可撤销。清理可能分批完成，未完成时请回来继续；不会仅清空本机就宣称成功。',confirmText:'确认申请',success:async final=>{if(final.confirm)await this.runCloudErasure('requestErasure')}})}})},
 async continueCloudErasure(){await this.runCloudErasure('continueErasure')},
 async runCloudErasure(action){if(this.data.privacyBusy)return;this.setData({privacyBusy:true});try{const result=await require('../../lib/cloud-privacy').privacyAction(action);this.setData({privacyStatus:result.status,privacyMessage:result.label})}catch(e){this.setData({privacyMessage:'云端清理未确认完成，请稍后重试。'})}finally{this.setData({privacyBusy:false})}},
 onLoad(q={}){const section=['privacy','help','about','membership','friends','local'].includes(q.section)?q.section:'privacy';this.setData({section,version:'0.1.7',membership:membershipView(),social:socialView()});if(section==='membership')track('subscription_page_viewed',{source:'settings'})},
 changeSection(e){this._serviceToken=(this._serviceToken||0)+1;this.setData({serviceBusy:false,serviceError:'',paymentLabel:'',shareMessage:'',receivedLikes:[],receivedLikesLoaded:false,receivedLikesCursor:''});this.onLoad({section:e.currentTarget.dataset.section})},
 placeVisibility(e){try{wx.setStorageSync('nature.showLocation',!!e.detail.value);this.setData({showLocation:!!e.detail.value})}catch(e){wx.showToast({title:'设置未保存',icon:'none'})}},
 copyFeedback(){wx.setClipboardData({data:'去大自然里 · 本地反馈模板\n版本：'+this.data.version+'\n问题描述：\n操作步骤：\n预期效果：\n请自行补充后发送给开发者；不要填写照片、精确位置、密码或密钥。'})},
 data:{section:'privacy',version:'0.1.7',showLocation:false,count:0,species:0,days:0,reduce:false,drafts:[],recent:[],notes:[],cleanup:0,clearing:false,exportPath:'',exportBusy:false,opsCode:'',opsBusy:false,opsMessage:'',opsResult:null,cloudCleanup:0,cloudCleanupBusy:false},
 _opsDate(days=0){const d=new Date();d.setDate(d.getDate()+days);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')},
 opsCodeInput(e){this.setData({opsCode:String(e.detail.value||'')})},
 async claimOperator(){if(this.data.opsBusy)return;this.setData({opsBusy:true,opsMessage:'',opsResult:null});try{const r=await wx.cloud.callFunction({name:'printAdmin',data:{action:'claim_operator',code:this.data.opsCode}});const body=r&&r.result;if(!body||body.status!=='ok')throw Object.assign(Error('激活失败'),{code:body&&body.code});this.setData({opsMessage:'已激活为运营。',opsCode:'',opsClaimed:true});wx.setStorageSync('nature.ops.claimed',true)}catch(e){this.setData({opsMessage:this._opsFriendly(e.code)||e.message||'激活失败，请重试。'})}finally{this.setData({opsBusy:false})}},
 _opsFriendly(code){const map={invalid_claim_code:'激活码不正确。',unauthenticated:'微信身份未确认，请重新进入小程序。',service_unavailable:'服务暂时不可用，请稍后重试。'};return map[code]},
 async runOpsAction(action,extra={}){if(this.data.opsBusy)return;this.setData({opsBusy:true,opsMessage:'',opsResult:null});try{const r=await wx.cloud.callFunction({name:'analytics-aggregate',data:{action,...extra}});const body=r&&r.result;if(!body||body.status!=='ok')throw Object.assign(Error('操作失败'),{code:body&&body.code});this.setData({opsResult:this._opsSummary(action,body),opsMessage:''})}catch(e){this.setData({opsMessage:this._opsFriendly(e.code)||e.message||'操作失败，请重试。'})}finally{this.setData({opsBusy:false})}},
 _opsSummary(action,body){if(action==='aggregate_day')return `已聚合 ${body.day}\n事件数 ${body.events}\n用户数 ${body.uniqueUsers}${body.truncated?'\n(已截断)':''}`;if(action==='dashboard')return `看板 ${body.from||''} ~ ${body.to||''}\n总事件 ${body.totals&&body.totals.events}\n日均活跃用户 ${body.dau&&body.dau.average}\n漏斗：开始${body.printFunnel&&body.printFunnel.started} → 下单${body.printFunnel&&body.printFunnel.orderCreated}`;if(action==='quota')return `Hunyuan 额度\n已用总计 ${body.usedTotal != null ? body.usedTotal : '未知'}\n剩余 ${body.freeQuotaRemaining != null ? body.freeQuotaRemaining : '未配置总额'}\n告警 ${body.alert?'是':'否'}`;return JSON.stringify(body)},
 opsAggregateYesterday(){return this.runOpsAction('aggregate_day',{date:this._opsDate(-1)})},
 opsDashboard(){const to=this._opsDate(0);const from=this._opsDate(-6);return this.runOpsAction('dashboard',{from,to})},
 opsQuota(){return this.runOpsAction('quota')},
 onShow(){this.setData({recognitionConsent:hasConsent(wx),recoveryConsent:recoveryConsent.allowed(wx),opsClaimed:!!wx.getStorageSync('nature.ops.claimed')});this.refresh()},
 async recoveryConsentChange(e){const accepted=!!e.detail.value;this.setData({recoveryBusy:true,recoveryMessage:'',recoveryConsent:false});try{await recoveryConsent.setRecoveryConsent(wx,accepted);this.setData({recoveryConsent:recoveryConsent.allowed(wx),recoveryMessage:accepted?'已开启，仅恢复本人已保存云端卡片。':'已关闭后续恢复；云端记录仍保留，可另行删除或申请账号清除。'})}catch(e){this.setData({recoveryConsent:recoveryConsent.allowed(wx),recoveryMessage:accepted?'授权未保存，尚未开启，请检查网络或本机空间。':e.code==='sync_revoke_pending'?'本次已停止恢复，撤销已排队；联网后重试。已发出的图片链接最长仍可用10分钟。':'隐私设置未完成：本机存储或网络异常，无法保证重启后保持关闭。请保持本页，联网并释放空间后再次关闭；尚不能视为撤销成功。'})}finally{this.setData({recoveryBusy:false})}},
 recognitionConsentChange(e){try{setConsent(!!e.detail.value,wx);this.setData({recognitionConsent:!!e.detail.value})}catch(e){wx.showToast({title:'设置未保存',icon:'none'})}},
 refresh(){const cards=app.getCards().filter(c=>c&&c.kind!=='example'&&!c.sample).map(c=>app.decorate(c)).filter(Boolean),cleanup=app.getCleanup().length;this.setData({showLocation:wx.getStorageSync('nature.showLocation')===true,count:cards.length,species:new Set(cards.map(c=>c.speciesId)).size,days:new Set(cards.filter(c=>c.createdAt).map(c=>c.date)).size,reduce:!!wx.getStorageSync('nature.reduceMotion'),drafts:app.getDrafts().slice().reverse().map(d=>({id:d.id,photoPath:d.photoPath,status:d.pendingCard?'待入册卡片':d.mode==='unknown'?'待确认物种':'待鉴别照片'})),recent:cards.slice().reverse().slice(0,12),notes:cards.map(c=>({id:c.id,zh:c.zh,text:wx.getStorageSync('nature.note.'+c.id)||''})).filter(n=>n.text),cleanup,cleanupState:cleanup?'等待清理':'无待清理文件',cloudCleanup:require('../../lib/cloud-cleanup').entries(wx).length})},
 motion(e){try{wx.setStorageSync('nature.reduceMotion',e.detail.value);this.setData({reduce:e.detail.value})}catch(e){wx.showToast({title:'设置未保存',icon:'none'})}},
 resume(e){try{app.selectDraft(e.currentTarget.dataset.id);wx.reLaunch({url:'/native/pages/observe/index'})}catch(e){wx.showToast({title:'恢复失败',icon:'none'})}},
 open(e){wx.navigateTo({url:'/native/pages/card/index?id='+e.currentTarget.dataset.id})},
 removeDraft(e){
  const id=e.currentTarget.dataset.id;
  wx.showModal({title:'删除这份草稿？',content:'未入册内容会删除，未被收藏引用的本地照片也会清理。',confirmText:'删除草稿',success:async r=>{
   if(!r.confirm)return;
   try{const failed=await app.deleteDraft(id);this.refresh();wx.showToast({title:failed.length?'草稿已删，照片稍后重试清理':'草稿已删除',icon:'none'})}
   catch(e){wx.showToast({title:'删除失败，请重试',icon:'none'})}
  }});
 },
 async retry(){try{await app.retryCleanup();this.refresh();wx.showToast({title:this.data.cleanup?'仍有文件待清理':'照片清理完成',icon:'none'})}catch(e){wx.showToast({title:'清理失败，请重试',icon:'none'})}},
 async retryCloudCleanup(){if(this.data.cloudCleanupBusy)return;this.setData({cloudCleanupBusy:true});try{const pending=await app.retryCloudCleanup();this.refresh();const left=Array.isArray(pending)?pending.length:0;wx.showToast({title:left?'仍有 '+left+' 条观察待云端清理':'云端照片清理已完成',icon:'none'})}catch(e){wx.showToast({title:'云端清理未成功，请稍后重试',icon:'none'})}finally{this.setData({cloudCleanupBusy:false})}},
 clear(){if(this.data.clearing)return;wx.showModal({title:'清除全部本地数据？',content:'会删除收藏、笔记、草稿和本地照片；此操作无法撤销。你可以先导出备份。',confirmText:'继续',success:r=>{if(!r.confirm)return;wx.showModal({title:'再次确认：永久清除',content:'确认删除本设备的全部自然观察记录及照片？其他应用数据不受影响。',confirmText:'永久清除',confirmColor:'#b03a26',success:async final=>{if(!final.confirm)return;this._exportToken=(this._exportToken||0)+1;this._exportText='';this.setData({clearing:true,exportPath:'',exportBusy:false});try{const failed=await app.clearLocalData();this._exportText='';this.setData({exportPath:''});this.refresh();wx.showToast({title:failed.length?'数据已清除，部分照片待重试':'本地数据已清除',icon:'none'})}catch(e){wx.showToast({title:'清除未完成，请重试',icon:'none'})}finally{this.setData({clearing:false})}}})}})},
 exportData(){if(this.data.clearing||this.data.exportBusy)return;const epoch=app.getDataEpoch(),token=this._exportToken=(this._exportToken||0)+1;this.setData({exportBusy:true});try{const contents=JSON.stringify(app.exportLocalData(),null,2);const filePath=wx.env.USER_DATA_PATH+'/nature-observations-'+Date.now()+'.json';wx.getFileSystemManager().writeFile({filePath,data:contents,encoding:'utf8',success:()=>{if(epoch!==app.getDataEpoch()||token!==this._exportToken||this.data.clearing){wx.getFileSystemManager().unlink({filePath});return;}this.setData({exportBusy:false});try{wx.setStorageSync('nature.export.files',(wx.getStorageSync('nature.export.files')||[]).concat([filePath]));this._exportText=contents;this.setData({exportPath:filePath});wx.showToast({title:'JSON备份已生成'})}catch(e){wx.getFileSystemManager().unlink({filePath});wx.showToast({title:'记录导出失败',icon:'none'})}},fail:()=>{this.setData({exportBusy:false});wx.showToast({title:'导出失败，请检查空间',icon:'none'})}})}catch(e){this.setData({exportBusy:false});wx.showToast({title:'导出失败，请重试',icon:'none'})}},
 saveBackup(){if(this.data.clearing||!this.data.exportPath)return;if(wx.shareFileMessage)wx.shareFileMessage({filePath:this.data.exportPath,fileName:'自然观察备份.json',fail:()=>wx.showToast({title:'未发送，文件仍在本机',icon:'none'})});else wx.showToast({title:'当前微信不支持文件发送，可复制JSON',icon:'none'})},
 copyBackup(){if(!this.data.clearing&&this._exportText)wx.setClipboardData({data:this._exportText})}
})
