const app=getApp(),model=require('../../lib/print-order'),cardExport=require('../../lib/card-export'),{decodeAsset}=require('../../lib/asset-decode'),{readableFront,readableOriginal}=require('../../lib/card-image');
Page({
 data:{rows:[],selected:[],ordered:[],quote:null,draft:null,busy:false,error:'',quality:'',previewPath:''},
 onLoad(){this._active=true},onShow(){this._active=true;this.refresh()},onHide(){this._active=false;this._token=(this._token||0)+1;this.setData({busy:false,previewPath:''})},onUnload(){this.onHide()},
 refresh(){const rows=model.printCandidates(app.getCards()),selected=model.reconcileSelection(wx.getStorageSync('nature.print.selection.v1'),rows);const cached=wx.getStorageSync('nature.print.draft.v1'),matches=cached?.draftStatus==='draft'&&cached.items?.length===24&&cached.items.every((item,i)=>item.cardId===selected[i]);this.setData({rows:rows.map(r=>({...r,selected:selected.includes(r.serverCardId)})),selected,ordered:selected.map(id=>rows.find(r=>r.serverCardId===id)),quote:null,draft:matches?cached:null,draftCached:!!matches})},
 changeSelection(selected){try{wx.setStorageSync('nature.print.selection.v1',selected);this._token=(this._token||0)+1;this.setData({rows:this.data.rows.map(r=>({...r,selected:selected.includes(r.serverCardId)})),selected,ordered:selected.map(id=>this.data.rows.find(r=>r.serverCardId===id)),quote:null,draft:null,error:'',previewPath:''})}catch(e){this.setData({error:'选卡顺序未保存，请检查本机空间后重试。'})}},
 toggle(e){if(this.data.busy)return;const row=this.data.rows.find(r=>r.id===e.currentTarget.dataset.id);if(!row?.eligible)return;const ids=this.data.selected.slice(),i=ids.indexOf(row.serverCardId);if(i>=0)ids.splice(i,1);else if(ids.length<24)ids.push(row.serverCardId);else{this.setData({error:'已选满24张，请先移除一张。'});return}this.changeSelection(ids)},
 move(e){if(!this.data.busy)this.changeSelection(model.moveSelection(this.data.selected,Number(e.currentTarget.dataset.index),Number(e.currentTarget.dataset.direction)))},
 invalidateCachedDraft(){try{wx.removeStorageSync('nature.print.draft.v1');return ''}catch(e){return ' 本机缓存清理未确认，请勿将缓存视为有效草稿。'}},
 async gifts(){if(this.data.busy)return;const token=this._token=(this._token||0)+1;this.setData({busy:true,error:''});try{const r=await require('../../lib/account-services').socialCall(wx,'listMemorialCopies');if(this._active&&token===this._token)this.setData({giftRows:model.printCandidates(r.copies||[])})}catch(e){if(token===this._token)this.setData({error:e.message})}finally{if(token===this._token)this.setData({busy:false})}},
 async quote(){if(this.data.busy||this.data.selected.length!==24)return;const token=this._token=(this._token||0)+1;this.setData({busy:true,error:'',quote:null,draft:null});try{const quote=await model.printCall(wx,'print_quote',{cardIds:this.data.selected});if(this._active&&token===this._token){const prior=wx.getStorageSync('nature.print.request.v1');this._key=prior?.quoteHash===quote.quoteHash?prior.key:'print_'+Date.now()+'_'+Math.random().toString(36).slice(2);wx.setStorageSync('nature.print.request.v1',{quoteHash:quote.quoteHash,key:this._key});this.setData({quote,quoteReview:model.reviewQuote(quote,this.data.selected,app.getCards().map(c=>app.decorate?app.decorate(c):c))})}}catch(e){if(token===this._token)this.setData({draft:null,draftCached:false,error:e.message+this.invalidateCachedDraft()})}finally{if(token===this._token)this.setData({busy:false})}},
 async saveDraft(){if(this.data.busy||!this.data.quote||!this.data.quoteReview?.valid)return;const token=this._token=(this._token||0)+1;this.setData({busy:true,error:''});try{const draft=await model.printCall(wx,'print_draft',{cardIds:this.data.selected,quoteHash:this.data.quote.quoteHash,idempotencyKey:this._key});if(!this._active||token!==this._token)return;wx.setStorageSync('nature.print.draft.v1',draft);this.setData({draft,draftCached:false})}catch(e){if(token===this._token)this.setData({draft:null,draftCached:false,error:(e.message||'草稿未存入本机，请重试。')+this.invalidateCachedDraft()})}finally{if(token===this._token)this.setData({busy:false})}},
 preview(e){if(this.data.busy)return;const row=this.data.ordered[Number(e.currentTarget.dataset.index)],raw=app.getCards().find(c=>c.serverCardId===row?.serverCardId);if(!raw)return;const card=app.decorate(raw),mode=e.currentTarget.dataset.side==='back'?'printBack':'printFront',plan=cardExport.exportPlan(card,mode),token=this._token=(this._token||0)+1,current=()=>this._active&&token===this._token;this.setData({busy:true,error:'',previewPath:'',quality:''},()=>wx.createSelectorQuery().in(this).select('#printCanvas').fields({node:true}).exec(async result=>{try{const canvas=result?.[0]?.node;if(!canvas)throw Error('预览画布暂不可用。');canvas.width=plan.width;canvas.height=plan.height;const info=await(mode==='printBack'?readableOriginal(wx,card):readableFront(wx,card)),decoded=await decodeAsset(canvas,info.path,current);if(!current())return;cardExport.render(canvas.getContext('2d'),card,plan,mode==='printBack'?null:decoded.image,mode==='printBack'?decoded.image:null);wx.canvasToTempFilePath({canvas,width:plan.width,height:plan.height,destWidth:plan.width,destHeight:plan.height,fileType:'png',success:r=>{if(current())this.setData({busy:false,previewPath:r.tempFilePath,quality:cardExport.printQuality(info,mode,card).message})},fail:()=>{if(current())this.setData({busy:false,error:'PNG未生成，请重试。'})}},this)}catch(e){if(current())this.setData({busy:false,error:'照片或艺术图无法读取；没有生成空白预览。请检查云端恢复授权或重新打开卡片。'})}}))},
 viewPreview(){if(this.data.previewPath)wx.previewImage({urls:[this.data.previewPath]})},back(){wx.navigateBack()}
});
